language: php

before_install:
  - sh -c "mkdir -p ${TRAVIS_BUILD_DIR}/travis/module-cache/`php-config --vernum`"
  
before_script:
  - MODULES="apcu.so:apcu-beta memcached.so:memcached" ./travis/modulecache.sh

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/travis/module-cache

script:
  - echo ":-)"

php:
  - 5.5
